name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: '35 5 * * 2'
  workflow_dispatch:

jobs:
  steve:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Trigger: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref}}"

      - uses: action/checkout@v4

      - name: List files
        run: |
          echo "Repo ${{ github.repository}} contains these files:"
          tree
