name: Reusable workflow demo

on: 
  workflow_dispatch:

jobs:
  caller:
    uses: mdo-test-org/hello-world-action/.github/workflows/hello-world-reusable.yml@main
    with:
      name: Jason

  output:
    runs-on: ubuntu-latest
    needs: ['caller']
    steps:
      - name: "Output Caller Time"
        run: |
          echo "Time: ${{ needs.caller.outputs.current-time }}"
